-- ============================================================
-- HelloBlog 初始化数据库 Schema
-- PostgreSQL + pgvector
-- ============================================================

-- 扩展
CREATE EXTENSION IF NOT EXISTS vector;

-- 枚举类型
CREATE TYPE record_status AS ENUM ('normal', 'hidden', 'deleted');
CREATE TYPE like_target_type AS ENUM ('post', 'comment');

-- ============================================================
-- 用户表
-- ============================================================
CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE,
  "password_hash" varchar(255),
  "avatar_url" text,
  "bio" text,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE INDEX "users_email_idx" ON "users" ("email");
CREATE INDEX "users_username_idx" ON "users" ("username");

-- ============================================================
-- 第三方登录关联表
-- ============================================================
CREATE TABLE "oauth_identities" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "provider" varchar(30) NOT NULL,
  "provider_user_id" varchar(100) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX "oauth_identities_provider_user_id_idx"
  ON "oauth_identities" ("provider", "provider_user_id");

CREATE UNIQUE INDEX "oauth_identities_user_provider_idx"
  ON "oauth_identities" ("user_id", "provider");

CREATE INDEX "oauth_identities_user_id_idx"
  ON "oauth_identities" ("user_id");

ALTER TABLE "oauth_identities"
  ADD CONSTRAINT "user_oauth_identities"
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- ============================================================
-- 博客文章表
-- ============================================================
CREATE TABLE "posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "title" varchar(200) NOT NULL,
  "summary" text,
  "content" text NOT NULL,
  "search_vector" tsvector,
  "like_count" integer NOT NULL DEFAULT 0,
  "comment_count" integer NOT NULL DEFAULT 0,
  "view_count" integer NOT NULL DEFAULT 0,
  "status" record_status NOT NULL DEFAULT 'normal',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

ALTER TABLE "posts"
  ADD CONSTRAINT "posts_user_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "posts_user_id_idx" ON "posts" ("user_id");
CREATE INDEX "posts_status_idx" ON "posts" ("status") WHERE "status" = 'normal';
CREATE INDEX "posts_created_at_idx" ON "posts" ("created_at" DESC);

-- 全文检索触发器
CREATE FUNCTION "posts_search_sync"()
RETURNS trigger AS $$
BEGIN
  NEW."search_vector" =
    setweight(to_tsvector('simple', coalesce(NEW."title", '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(NEW."summary", '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(NEW."content", '')), 'C');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "posts_search_sync_trigger"
  BEFORE INSERT OR UPDATE OF "title", "summary", "content"
  ON "posts"
  FOR EACH ROW
  EXECUTE FUNCTION "posts_search_sync"();

CREATE INDEX "posts_search_vector_idx" ON "posts" USING GIN ("search_vector");

-- ============================================================
-- 文章嵌入向量表（语义检索）
-- ============================================================
CREATE TABLE "post_embeddings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" bigint UNIQUE NOT NULL,
  "embedding" vector(1024) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE INDEX "post_embeddings_embedding_hnsw_idx"
  ON "post_embeddings" USING hnsw ("embedding" vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

ALTER TABLE "post_embeddings"
  ADD CONSTRAINT "post_embedding_ref"
  FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- ============================================================
-- 评论表
-- ============================================================
CREATE TABLE "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "parent_id" bigint,
  "content" text NOT NULL,
  "like_count" integer NOT NULL DEFAULT 0,
  "status" record_status NOT NULL DEFAULT 'normal',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

ALTER TABLE "comments"
  ADD CONSTRAINT "comments_post_id_fk"
  FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments"
  ADD CONSTRAINT "comments_user_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments"
  ADD CONSTRAINT "comments_parent_id_fk"
  FOREIGN KEY ("parent_id") REFERENCES "comments" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "comments_post_id_idx" ON "comments" ("post_id");
CREATE INDEX "comments_user_id_idx" ON "comments" ("user_id");
CREATE INDEX "comments_parent_id_idx" ON "comments" ("parent_id");

-- ============================================================
-- 点赞表
-- ============================================================
CREATE TABLE "likes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "target_type" like_target_type NOT NULL,
  "target_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

ALTER TABLE "likes"
  ADD CONSTRAINT "likes_user_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

CREATE UNIQUE INDEX "likes_user_target_idx"
  ON "likes" ("user_id", "target_type", "target_id");

CREATE INDEX "likes_target_idx"
  ON "likes" ("target_type", "target_id");

-- ============================================================
-- 全文检索函数
-- ============================================================
CREATE FUNCTION "full_text_search_posts"(
  "query_text" text,
  "match_count" integer DEFAULT 20
)
RETURNS TABLE (
  "post_id" bigint,
  "title" varchar(200),
  "summary" text,
  "created_at" timestamp,
  "rank" integer,
  "score" double precision
) AS $$
WITH "input" AS (
  SELECT
    nullif(trim("query_text"), '') AS "q",
    greatest("match_count", 1) AS "limit_n"
),
"text_query" AS (
  SELECT websearch_to_tsquery('simple', "q") AS "tsq"
  FROM "input"
  WHERE "q" IS NOT NULL
)
SELECT
  p."id",
  p."title",
  p."summary",
  p."created_at",
  row_number() OVER (
    ORDER BY ts_rank_cd(p."search_vector", tq."tsq", 32) DESC, p."created_at" DESC
  )::integer AS "rank",
  ts_rank_cd(p."search_vector", tq."tsq", 32)::double precision AS "score"
FROM "posts" p
CROSS JOIN "text_query" tq
WHERE p."status" = 'normal'
  AND p."search_vector" @@ tq."tsq"
ORDER BY "score" DESC, p."created_at" DESC
LIMIT (SELECT "limit_n" FROM "input");
$$ LANGUAGE sql STABLE;

-- ============================================================
-- 语义检索函数
-- ============================================================
CREATE FUNCTION "vector_search_posts"(
  "query_embedding" vector(1024),
  "match_count" integer DEFAULT 20
)
RETURNS TABLE (
  "post_id" bigint,
  "title" varchar(200),
  "summary" text,
  "created_at" timestamp,
  "rank" integer,
  "distance" double precision
) AS $$
WITH "input" AS (
  SELECT
    "query_embedding" AS "embedding",
    greatest("match_count", 1) AS "limit_n"
)
SELECT
  p."id",
  p."title",
  p."summary",
  p."created_at",
  row_number() OVER (
    ORDER BY pe."embedding" <=> i."embedding", p."created_at" DESC
  )::integer AS "rank",
  (pe."embedding" <=> i."embedding")::double precision AS "distance"
FROM "input" i
JOIN "post_embeddings" pe ON i."embedding" IS NOT NULL
JOIN "posts" p ON p."id" = pe."post_id"
WHERE p."status" = 'normal'
ORDER BY pe."embedding" <=> i."embedding", p."created_at" DESC
LIMIT (SELECT "limit_n" FROM "input");
$$ LANGUAGE sql STABLE;

-- ============================================================
-- 混合检索函数 (RRF)
-- ============================================================
CREATE FUNCTION "hybrid_search_posts"(
  "query_text" text,
  "query_embedding" vector(1024) DEFAULT NULL,
  "match_count" integer DEFAULT 20,
  "candidate_count" integer DEFAULT 100,
  "text_weight" double precision DEFAULT 0.45,
  "vector_weight" double precision DEFAULT 0.55,
  "rrf_k" integer DEFAULT 60
)
RETURNS TABLE (
  "post_id" bigint,
  "title" varchar(200),
  "summary" text,
  "created_at" timestamp,
  "score" double precision
) AS $$
WITH "input" AS (
  SELECT
    greatest("match_count", 1) AS "limit_n",
    greatest("candidate_count", "match_count", 1) AS "candidate_n",
    greatest("rrf_k", 1) AS "rank_k",
    greatest("text_weight", 0.0) AS "text_w",
    greatest("vector_weight", 0.0) AS "vector_w"
),
"ranked_candidates" AS (
  SELECT
    ft."post_id",
    i."text_w" / (i."rank_k" + ft."rank") AS "score_part"
  FROM "input" i
  CROSS JOIN "full_text_search_posts"("query_text", i."candidate_n") ft

  UNION ALL

  SELECT
    vs."post_id",
    i."vector_w" / (i."rank_k" + vs."rank") AS "score_part"
  FROM "input" i
  CROSS JOIN "vector_search_posts"("query_embedding", i."candidate_n") vs
),
"combined" AS (
  SELECT
    "post_id",
    sum("score_part")::double precision AS "score"
  FROM "ranked_candidates"
  GROUP BY "post_id"
)
SELECT
  p."id",
  p."title",
  p."summary",
  p."created_at",
  c."score"
FROM "combined" c
JOIN "posts" p ON p."id" = c."post_id"
ORDER BY c."score" DESC, p."created_at" DESC
LIMIT (SELECT "limit_n" FROM "input");
$$ LANGUAGE sql STABLE;

-- ============================================================
-- 通知表
-- ============================================================
CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "type" varchar(30) NOT NULL DEFAULT 'comment',
  "title" varchar(200) NOT NULL DEFAULT '',
  "content" text NOT NULL DEFAULT '',
  "from_user_id" bigint,
  "post_id" bigint,
  "is_read" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE INDEX "notifications_user_id_idx" ON "notifications" ("user_id", "is_read");

-- ============================================================
-- 友情链接表
-- ============================================================
CREATE TABLE "links" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "url" varchar(500) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);
